services:
    db:
        image: mysql:latest
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        restart: unless-stopped

    adminer:
        image: adminer:latest
        container_name: adminer
        ports:
            - "8080:8080"
        depends_on:
            - db
        restart: unless-stopped

    minio:
        image: quay.io/minio/minio:latest
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - minio_data:/data
        command: server /data --console-address ":9001"
        restart: unless-stopped

volumes:
    db_data:
        driver: local
    minio_data:
        driver: local
