services:
    quizify-api:
        image: quizify-api:v1
        ports:
            - "8000:8000"
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
        environment:
            NODE_ENV: production
            DB_CONNECTION: mysql
            DB_HOST: ${MYSQL_HOST}
            DB_PORT: ${MYSQL_PORT}
            DB_DATABASE: ${MYSQL_DATABASE}
            DB_USERNAME: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
        depends_on:
            - mysql
        networks:
            - quizify-network
        restart: always

    mysql:
        image: mysql:8.0
        container_name: quizify-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - quizify-network

        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s

    adminer:
        image: adminer
        container_name: quizify-adminer
        restart: on-failure
        ports:
            - "8080:8080"
        depends_on:
            - mysql
        networks:
            - quizify-network
        profiles: ["admin"]

    minio:
        image: minio/minio:latest
        container_name: quizify-minio
        restart: always
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server /data --console-address ":9001"
        networks:
            - quizify-network
        volumes:
            - minio_data:/data

networks:
    quizify-network:
        external: true
        name: quizify-network

volumes:
    mysql_data:
    minio_data:
