services:
    quizify-api:
        image: quizify-api:v1
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
        environment:
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_KEY: ${APP_KEY}
            APP_DEBUG: ${APP_DEBUG}
            APP_FRONTEND_URL: ${APP_FRONTEND_URL}
            APP_TIMEZONE: ${APP_TIMEZONE}
            APP_URL: ${APP_URL}

            APP_LOCALE: ${APP_LOCALE}
            APP_FALLBACK_LOCALE: ${APP_FALLBACK_LOCALE}
            APP_FAKER_LOCALE: ${APP_FAKER_LOCALE}

            FILESYSTEM_DISK: ${FILESYSTEM_DISK}
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
            MINIO_ENDPOINT: ${MINIO_ENDPOINT}
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
            MINIO_BUCKET: ${MINIO_BUCKET}

            APP_MAINTENANCE_DRIVER: ${APP_MAINTENANCE_DRIVER}

            PHP_CLI_SERVER_WORKERS: ${PHP_CLI_SERVER_WORKERS}

            BCRYPT_ROUNDS: ${BCRYPT_ROUNDS}

            LOG_CHANNEL: ${LOG_CHANNEL}
            LOG_STACK: ${LOG_STACK}
            LOG_DEPRECATIONS_CHANNEL: ${LOG_DEPRECATIONS_CHANNEL}
            LOG_LEVEL: ${LOG_LEVEL}

            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

            MYSQL_CONNECTION: ${MYSQL_CONNECTION}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

            SESSION_DRIVER: ${SESSION_DRIVER}
            SESSION_LIFETIME: ${SESSION_LIFETIME}
            SESSION_ENCRYPT: ${SESSION_ENCRYPT}
            SESSION_PATH: ${SESSION_PATH}
            SESSION_DOMAIN: ${SESSION_DOMAIN}

            BROADCAST_CONNECTION: ${BROADCAST_CONNECTION}
            QUEUE_CONNECTION: ${QUEUE_CONNECTION}
            CACHE_STORE: ${CACHE_STORE}
            CACHE_PREFIX: ${CACHE_PREFIX}

            MEMCACHED_HOST: ${MEMCACHED_HOST}

            REDIS_CLIENT: ${REDIS_CLIENT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_PORT: ${REDIS_PORT}

            MAIL_MAILER: ${MAIL_MAILER}
            MAIL_SCHEME: ${MAIL_SCHEME}
            MAIL_HOST: ${MAIL_HOST}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
            MAIL_FROM_NAME: ${MAIL_FROM_NAME}

            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
            AWS_BUCKET: ${AWS_BUCKET}
            AWS_USE_PATH_STYLE_ENDPOINT: ${AWS_USE_PATH_STYLE_ENDPOINT}

            VITE_APP_NAME: ${VITE_APP_NAME}

            ADMIN_USERNAME: ${ADMIN_USERNAME}
            ADMIN_FIRSTNAME: ${ADMIN_FIRSTNAME}
            ADMIN_LASTNAME: ${ADMIN_LASTNAME}
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}
            ADMIN_PROFILE_PHOTO: ${ADMIN_PROFILE_PHOTO}

            SCOUT_DRIVER: ${SCOUT_DRIVER}
            ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
            ELASTICSEARCH_INDEX: ${ELASTICSEARCH_INDEX}

            NODE_ENV: production
        depends_on:
            - mysql
        networks:
            - quizify-network
        restart: always
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"

    mysql:
        image: mysql:8.0
        container_name: quizify-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - quizify-network

        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s

    adminer:
        image: adminer
        container_name: quizify-adminer
        restart: on-failure
        ports:
            - "8080:8080"
        depends_on:
            - mysql
        networks:
            - quizify-network
        profiles: ["admin"]

    minio:
        image: minio/minio:latest
        container_name: quizify-minio
        restart: always
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server /data --console-address ":9001"
        networks:
            - quizify-network
        volumes:
            - minio_data:/data

    scheduler:
        build: .
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        command: >
            sh -c "while true; do
            php artisan schedule:run
            sleep 60
            done"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        container_name: quizify-elasticsearch
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        networks:
            - quizify-network
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'",
                ]
            interval: 10s
            timeout: 10s
            retries: 3

networks:
    quizify-network:
        external: true
        name: quizify-network

volumes:
    mysql_data:
    minio_data:
    elasticsearch_data:
