name: Quizify API CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: quizify_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: xdebug

    - name: Copy .env
      run: cp .env.example .env.testing

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Generate key
      run: php artisan key:generate --env=testing

    - name: Configure environment
      run: |
        echo "APP_ENV=testing" >> .env.testing
        echo "DB_CONNECTION=mysql" >> .env.testing
        echo "DB_HOST=127.0.0.1" >> .env.testing
        echo "DB_PORT=3306" >> .env.testing
        echo "DB_DATABASE=quizify_test" >> .env.testing
        echo "DB_USERNAME=root" >> .env.testing
        echo "DB_PASSWORD=password" >> .env.testing

    - name: Run migrations
      run: php artisan migrate --env=testing --force

    - name: Run tests
      run: php artisan test

    - name: Run code quality checks
      run: |
        composer require --dev laravel/pint
        ./vendor/bin/pint --test

  # deploy:
  #   needs: test
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #   - uses: actions/checkout@v3
  #
  #   # Ajoutez ici vos étapes de déploiement selon votre hébergement
  #   - name: Deploy to production
  #     run: echo "Déploiement en production - à configurer"
